/* WebHub India — seed dataset
   300 real, verified websites/services across every major category.
   Every category has a `subCategories` list, and every website
   entry has a matching `sub` field.
   Structured so it can be extended indefinitely. Every entry below
   is a real, currently operating website. */

const CATEGORIES = [
  { id: "government", label: "Government", icon: "landmark", subCategories: [
    "Identity & Documents", "Taxation", "Transport & Vehicle", "Elections & Civic", "Postal & Courier", "Legal & Judiciary", "Health & Safety", "Employment & Welfare", "Portals & Services"
  ]},
  { id: "finance", label: "Banking & Finance", icon: "banknote", subCategories: [
    "Banking", "Payments", "Investments", "Insurance", "Tax Services", "Cryptocurrency", "Regulatory", "Loans & Lending"
  ]},
  { id: "shopping", label: "Shopping", icon: "shopping-bag", subCategories: [
    "Marketplace", "Fashion & Lifestyle", "Beauty & Personal Care", "Grocery & Quick Commerce", "Home & Furniture"
  ]},
  { id: "education", label: "Education", icon: "graduation-cap", subCategories: [
    "School Learning", "Exam Preparation", "Higher Education", "Free Courses & MOOCs", "Scholarships"
  ]},
  { id: "jobs", label: "Jobs & Careers", icon: "briefcase", subCategories: [
    "Job Portals", "Professional Networking", "Internships", "Government Jobs", "Freelancing"
  ]},
  { id: "travel", label: "Travel & Transport", icon: "plane", subCategories: [
    "Flights & Hotels", "Trains & Buses", "Airlines", "Navigation & Maps", "Local Transit", "Tourism"
  ]},
  { id: "entertainment", label: "Entertainment", icon: "clapperboard", subCategories: [
    "Video Streaming", "Music & Podcasts", "Live Events & Tickets", "Video Sharing"
  ]},
  { id: "news", label: "News & Media", icon: "newspaper", subCategories: [
    "National News", "Business & Markets", "Sports News"
  ]},
  { id: "health", label: "Health", icon: "heart-pulse", subCategories: [
    "Doctor Consultation", "Pharmacy & Medicine", "Hospitals & Research", "Government Health Info", "Fitness & Wellness"
  ]},
  { id: "food", label: "Food & Grocery", icon: "utensils", subCategories: [
    "Food Delivery", "Grocery Delivery", "Specialty Food"
  ]},
  { id: "ai", label: "AI Tools", icon: "sparkles", subCategories: [
    "AI Assistants", "AI Search", "Indian AI", "AI Creative Tools", "AI Developer Tools"
  ]},
  { id: "social", label: "Social & Messaging", icon: "message-circle", subCategories: [
    "Messaging", "Social Networking", "Regional Social"
  ]},
  { id: "realestate", label: "Real Estate", icon: "home", subCategories: [
    "Property Listings", "Brokerage-Free", "Interior Design & Home Services"
  ]},
  { id: "utilities", label: "Utilities & Bills", icon: "zap", subCategories: [
    "Bill Payments", "Telecom Recharge"
  ]},
  { id: "productivity", label: "Productivity & Dev", icon: "layout-grid", subCategories: [
    "Code & Dev", "Cloud Storage", "Docs & Notes", "Design Tools", "PDF Tools", "Video Conferencing", "Hosting & Deployment", "Team Collaboration"
  ]},
];

const WEBSITES = [
  // ---------------- GOVERNMENT ----------------

   // ---------------- Identity & Documents ----------------
 { id: 1, name: "UIDAI (Aadhaar)", url: "https://uidai.gov.in", category: "government", sub: "Identity & Documents", desc: "Official portal to enroll, update or download your Aadhaar card.", tags: ["aadhaar", "identity"], verified: true, popular: true, trending: true },
{ id: 2, name: "myAadhaar", url: "https://myaadhaar.uidai.gov.in", category: "government", sub: "Identity & Documents", desc: "Self-service portal to manage your Aadhaar details, update address, and check status online.", tags: ["aadhaar", "identity", "self-service"], verified: true, popular: true, trending: true },
{ id: 3, name: "DigiLocker", url: "https://www.digilocker.gov.in", category: "government", sub: "Identity & Documents", desc: "Cloud-based platform to store, access and share verified government documents digitally.", tags: ["documents", "digital locker", "identity"], verified: true, popular: true, trending: true },
{ id: 4, name: "PAN / Income Tax", url: "https://www.incometax.gov.in", category: "government", sub: "Identity & Documents", desc: "Official e-filing portal for PAN services, income tax returns and related tax filings.", tags: ["pan", "tax", "income tax"], verified: true, popular: true, trending: false },
{ id: 5, name: "Passport Seva", url: "https://passportindia.gov.in", category: "government", sub: "Identity & Documents", desc: "Apply for a new passport, renew, or track your passport application status online.", tags: ["passport", "travel documents"], verified: true, popular: true, trending: false },
{ id: 6, name: "Birth & Death Registration (CRS)", url: "https://crsorgi.gov.in", category: "government", sub: "Identity & Documents", desc: "Civil Registration System portal for registering and obtaining birth and death certificates.", tags: ["birth certificate", "death certificate", "crs"], verified: true, popular: false, trending: false },
{ id: 7, name: "ABHA Health ID", url: "https://abdm.gov.in", category: "government", sub: "Identity & Documents", desc: "Create your Ayushman Bharat Health Account to link and access digital health records.", tags: ["health id", "abha", "healthcare"], verified: true, popular: true, trending: true },
{ id: 8, name: "Jeevan Pramaan", url: "https://jeevanpramaan.gov.in", category: "government", sub: "Identity & Documents", desc: "Digital life certificate portal for pensioners to submit proof of life online.", tags: ["life certificate", "pension"], verified: true, popular: false, trending: false },
{ id: 9, name: "eSign", url: "https://www.esign.gov.in", category: "government", sub: "Identity & Documents", desc: "Aadhaar-based electronic signature service to digitally sign documents online.", tags: ["esign", "digital signature"], verified: true, popular: false, trending: false },

 // ---------------- Taxation ----------------
 { id: 10, name: "Income Tax Department", url: "https://www.incometax.gov.in", category: "government", sub: "Taxation", desc: "Official portal for filing Income Tax Returns, refunds, PAN services, and tax-related services.", tags: ["income tax", "itr", "pan", "refund"], verified: true, popular: true, trending: false },
{ id: 11, name: "GST Portal", url: "https://www.gst.gov.in", category: "government", sub: "Taxation", desc: "Official GST portal for registration, return filing, payments, and taxpayer services.", tags: ["gst", "tax", "returns", "registration"], verified: true, popular: true, trending: false },
{ id: 12, name: "GST e-Way Bill", url: "https://ewaybillgst.gov.in", category: "government", sub: "Taxation", desc: "Generate and manage e-Way Bills for transportation of goods under GST.", tags: ["eway bill", "gst", "transport"], verified: true, popular: true, trending: false },
{ id: 13, name: "GST Registration", url: "https://services.gst.gov.in", category: "government", sub: "Taxation", desc: "Official portal for GST registration and taxpayer onboarding.", tags: ["gst registration", "business", "taxpayer"], verified: true, popular: false, trending: false },
{ id: 14, name: "TIN NSDL", url: "https://www.tin-nsdl.com", category: "government", sub: "Taxation", desc: "Portal for PAN, TAN, TDS, and tax information services.", tags: ["pan", "tan", "tds", "nsdl"], verified: true, popular: true, trending: false },
{ id: 15, name: "TRACES", url: "https://www.tdscpc.gov.in", category: "government", sub: "Taxation", desc: "Portal for TDS/TCS statements, Form 16, and tax corrections.", tags: ["traces", "tds", "tcs", "form 16"], verified: true, popular: false, trending: false },
{ id: 16, name: "CBIC", url: "https://www.cbic.gov.in", category: "government", sub: "Taxation", desc: "Official portal for GST, Customs, notifications, and indirect tax administration.", tags: ["cbic", "customs", "gst", "indirect tax"], verified: true, popular: false, trending: false },

 // ---------------- Transport & Vehicle ----------------
{ id: 17, name: "Parivahan Sewa", url: "https://parivahan.gov.in", category: "government", sub: "Transport & Vehicle", desc: "Official portal for driving licence, vehicle registration, permits, and transport-related citizen services.", tags: ["parivahan", "driving licence", "vehicle"], verified: true, popular: true, trending: false },
{ id: 18, name: "VAHAN", url: "https://vahan.parivahan.gov.in", category: "government", sub: "Transport & Vehicle", desc: "Vehicle registration services, RC details, ownership, and vehicle-related information.", tags: ["vahan", "rc", "vehicle registration"], verified: true, popular: true, trending: false },
{ id: 19, name: "SARATHI", url: "https://sarathi.parivahan.gov.in", category: "government", sub: "Transport & Vehicle", desc: "Driving licence application, renewal, learner licence, and related transport services.", tags: ["sarathi", "driving licence", "learner licence"], verified: true, popular: true, trending: false },
{ id: 20, name: "FASTag", url: "https://fastag.ihmcl.com", category: "government", sub: "Transport & Vehicle", desc: "Official FASTag portal for toll payments, recharge, and account management.", tags: ["fastag", "toll", "highway"], verified: true, popular: true, trending: false },
{ id: 21, name: "National Highways Authority", url: "https://nhai.gov.in", category: "government", sub: "Transport & Vehicle", desc: "Official portal of NHAI for national highways, toll information, and infrastructure updates.", tags: ["nhai", "highway", "roads"], verified: true, popular: false, trending: false },
{ id: 22, name: "Indian Railways", url: "https://indianrailways.gov.in", category: "government", sub: "Transport & Vehicle", desc: "Official Indian Railways portal with railway services, information, and announcements.", tags: ["railways", "train", "indian railways"], verified: true, popular: true, trending: false },
{ id: 23, name: "IRCTC", url: "https://www.irctc.co.in", category: "government", sub: "Transport & Vehicle", desc: "Official portal for train ticket booking, tourism, catering, and railway services.", tags: ["irctc", "train booking", "railway"], verified: true, popular: true, trending: false },
{ id: 24, name: "DigiYatra", url: "https://www.digiyatra.gov.in", category: "government", sub: "Transport & Vehicle", desc: "Digital identity-based airport travel platform for seamless and paperless passenger experience.", tags: ["digiyatra", "airport", "travel"], verified: true, popular: true, trending: false },

 // ---------------- Elections & Civic ----------------
 { id: 25, name: "Election Commission of India", url: "https://eci.gov.in", category: "government", sub: "Elections & Civic", desc: "Official Election Commission portal for elections, voter information, and electoral services.", tags: ["eci", "election", "voter"], verified: true, popular: true, trending: false },
{ id: 26, name: "Voters Service Portal", url: "https://voters.eci.gov.in", category: "government", sub: "Elections & Civic", desc: "Portal for voter registration, voter ID correction, status tracking, and electoral services.", tags: ["voter id", "registration", "epic"], verified: true, popular: true, trending: false },
{ id: 27, name: "National Voters Service Portal", url: "https://www.nvsp.in", category: "government", sub: "Elections & Civic", desc: "Official NVSP portal for voter registration, corrections, and election-related services.", tags: ["nvsp", "voter", "election"], verified: true, popular: true, trending: false },
{ id: 28, name: "e-EPIC Download", url: "https://voters.eci.gov.in", category: "government", sub: "Elections & Civic", desc: "Download your digital Elector Photo Identity Card (e-EPIC) online.", tags: ["e-epic", "digital voter id", "epic"], verified: true, popular: true, trending: false },
{ id: 29, name: "MyGov", url: "https://www.mygov.in", category: "government", sub: "Elections & Civic", desc: "Citizen engagement platform for government initiatives, discussions, and public participation.", tags: ["mygov", "citizen", "government"], verified: true, popular: true, trending: false },
{ id: 30, name: "National Portal of India", url: "https://www.india.gov.in", category: "government", sub: "Elections & Civic", desc: "Official gateway to Indian Government services, departments, and citizen resources.", tags: ["india portal", "government", "citizen services"], verified: true, popular: true, trending: false },

 // ---------------- Postal & Courier----------------
 { id: 31, name: "India Post", url: "https://www.indiapost.gov.in", category: "government", sub: "Postal & Courier", desc: "Official portal for postal services, mail, parcels, speed post, and post office information.", tags: ["india post", "post office", "mail"], verified: true, popular: true, trending: false },
{ id: 32, name: "India Post Tracking", url: "https://www.indiapost.gov.in", category: "government", sub: "Postal & Courier", desc: "Track Speed Post, registered post, parcels, and other postal consignments online.", tags: ["tracking", "speed post", "parcel"], verified: true, popular: true, trending: false },
{ id: 33, name: "Post Office Savings", url: "https://www.indiapost.gov.in", category: "government", sub: "Postal & Courier", desc: "Access information about Post Office Savings Schemes, deposits, and financial services.", tags: ["post office savings", "savings", "deposit"], verified: true, popular: false, trending: false },
{ id: 34, name: "India Post Payments Bank", url: "https://www.ippbonline.com", category: "government", sub: "Postal & Courier", desc: "Official portal for India Post Payments Bank banking, digital payments, and financial services.", tags: ["ippb", "payments bank", "banking"], verified: true, popular: true, trending: false },

 // ---------------- Legal & Judiciary----------------
 { id: 35, name: "Supreme Court of India", url: "https://www.sci.gov.in", category: "government", sub: "Legal & Judiciary", desc: "Official portal for Supreme Court cases, judgments, notices, and judicial services.", tags: ["supreme court", "judgments", "cases"], verified: true, popular: true, trending: false },
{ id: 36, name: "eCourts", url: "https://ecourts.gov.in", category: "government", sub: "Legal & Judiciary", desc: "Access case status, cause lists, court orders, and district court services online.", tags: ["ecourts", "case status", "court"], verified: true, popular: true, trending: false },
{ id: 37, name: "India Code", url: "https://www.indiacode.nic.in", category: "government", sub: "Legal & Judiciary", desc: "Official repository of Central Acts, rules, and legal documents of India.", tags: ["india code", "acts", "laws"], verified: true, popular: true, trending: false },
{ id: 38, name: "National Judicial Data Grid", url: "https://njdg.ecourts.gov.in", category: "government", sub: "Legal & Judiciary", desc: "View judicial statistics, pending cases, and court performance data across India.", tags: ["njdg", "judicial data", "pending cases"], verified: true, popular: false, trending: false },
{ id: 39, name: "Department of Justice", url: "https://doj.gov.in", category: "government", sub: "Legal & Judiciary", desc: "Official portal for justice administration, judicial reforms, and legal initiatives.", tags: ["department of justice", "judiciary", "legal"], verified: true, popular: false, trending: false },
{ id: 40, name: "National Legal Services Authority", url: "https://nalsa.gov.in", category: "government", sub: "Legal & Judiciary", desc: "Provides free legal aid, legal awareness, and access to justice for eligible citizens.", tags: ["nalsa", "legal aid", "justice"], verified: true, popular: true, trending: false },

  // ---------------- Health & Safety----------------
  { id: 41, name: "Ministry of Health", url: "https://www.mohfw.gov.in", category: "government", sub: "Health & Safety", desc: "Official portal of the Ministry of Health & Family Welfare for healthcare policies, programs, and public health services.", tags: ["health", "mohfw", "family welfare"], verified: true, popular: true, trending: false },
{ id: 42, name: "CoWIN", url: "https://www.cowin.gov.in", category: "government", sub: "Health & Safety", desc: "Official platform for vaccination certificates, immunization records, and health services.", tags: ["cowin", "vaccination", "certificate"], verified: true, popular: true, trending: false },
{ id: 43, name: "Ayushman Bharat", url: "https://beneficiary.nha.gov.in", category: "government", sub: "Health & Safety", desc: "Check PM-JAY eligibility, beneficiary status, and access Ayushman Bharat health scheme services.", tags: ["ayushman bharat", "pmjay", "health insurance"], verified: true, popular: true, trending: false },
{ id: 44, name: "National Health Authority", url: "https://nha.gov.in", category: "government", sub: "Health & Safety", desc: "Official portal of the National Health Authority for digital health and PM-JAY initiatives.", tags: ["nha", "health authority", "pmjay"], verified: true, popular: true, trending: false },
{ id: 45, name: "ICMR", url: "https://www.icmr.gov.in", category: "government", sub: "Health & Safety", desc: "Official portal of the Indian Council of Medical Research for medical research, guidelines, and publications.", tags: ["icmr", "medical research", "health"], verified: true, popular: true, trending: false },
{ id: 46, name: "ABDM", url: "https://abdm.gov.in", category: "government", sub: "Health & Safety", desc: "Ayushman Bharat Digital Mission portal for ABHA IDs and digital health ecosystem services.", tags: ["abdm", "abha", "digital health"], verified: true, popular: true, trending: false },
{ id: 47, name: "National Centre for Disease Control", url: "https://ncdc.mohfw.gov.in", category: "government", sub: "Health & Safety", desc: "Official portal for disease surveillance, outbreak updates, and public health guidance.", tags: ["ncdc", "disease control", "public health"], verified: true, popular:false, trending:false },
{ id: 48, name: "National Disaster Management Authority", url: "https://ndma.gov.in", category: "government", sub: "Health & Safety", desc: "Official portal for disaster preparedness, emergency management, and safety guidelines.", tags: ["ndma", "disaster", "emergency"], verified: true, popular: true, trending: false },

   // ---------------- Employment & Welfare----------------
   { id: 49, name: "EPFO", url: "https://www.epfindia.gov.in", category: "government", sub: "Employment & Welfare", desc: "Official Employees' Provident Fund portal for PF balance, claims, UAN, and pension services.", tags: ["epfo", "pf", "uan"], verified: true, popular: true, trending: false },
{ id: 50, name: "ESIC", url: "https://www.esic.gov.in", category: "government", sub: "Employment & Welfare", desc: "Official portal for Employees' State Insurance benefits, registration, and healthcare services.", tags: ["esic", "insurance", "employee"], verified: true, popular: true, trending: false },
{ id: 51, name: "e-Shram", url: "https://eshram.gov.in", category: "government", sub: "Employment & Welfare", desc: "National database and welfare portal for unorganized workers in India.", tags: ["e-shram", "labour", "workers"], verified: true, popular: true, trending: false },
{ id: 52, name: "National Career Service", url: "https://www.ncs.gov.in", category: "government", sub: "Employment & Welfare", desc: "Official job portal offering employment opportunities, career guidance, and skill services.", tags: ["ncs", "jobs", "career"], verified: true, popular: true, trending: false },
{ id: 53, name: "PM Kisan", url: "https://pmkisan.gov.in", category: "government", sub: "Employment & Welfare", desc: "Official portal for PM-KISAN scheme registration, beneficiary status, and farmer assistance.", tags: ["pm kisan", "farmer", "scheme"], verified: true, popular: true, trending: false },
{ id: 54, name: "PM Jan Dhan Yojana", url: "https://pmjdy.gov.in", category: "government", sub: "Employment & Welfare", desc: "Official portal for Pradhan Mantri Jan Dhan Yojana banking and financial inclusion scheme.", tags: ["jan dhan", "bank account", "financial inclusion"], verified: true, popular: true, trending: false },
{ id: 55, name: "Atal Pension Yojana", url: "https://www.npscra.nsdl.co.in", category: "government", sub: "Employment & Welfare", desc: "Official portal for Atal Pension Yojana registration, contributions, and pension services.", tags: ["atal pension", "apy", "pension"], verified: true, popular: true, trending: false },
{ id: 56, name: "National Pension System", url: "https://enps.nsdl.com", category: "government", sub: "Employment & Welfare", desc: "Official eNPS portal for National Pension System registration and account management.", tags: ["nps", "pension", "enps"], verified: true, popular: true, trending: false },
{ id: 57, name: "Skill India", url: "https://www.skillindia.gov.in", category: "government", sub: "Employment & Welfare", desc: "Official portal for skill development, vocational training, and certification programs.", tags: ["skill india", "training", "jobs"], verified: true, popular: true, trending: false },
    // ---------------- Portals & Services----------------
{ id: 58, name: "UMANG", url: "https://web.umang.gov.in", category: "government", sub: "Portals & Services", desc: "Unified Mobile Application for New-age Governance providing access to hundreds of government services.", tags: ["umang", "government services", "citizen"], verified: true, popular: true, trending: false },
{ id: 59, name: "CSC Digital Seva", url: "https://www.csc.gov.in", category: "government", sub: "Portals & Services", desc: "Official Common Services Centres portal offering digital government and citizen services.", tags: ["csc", "digital seva", "services"], verified: true, popular: true, trending: false },
{ id: 60, name: "National Portal of India", url: "https://www.india.gov.in", category: "government", sub: "Portals & Services", desc: "Official gateway to Indian Government services, departments, and citizen resources.", tags: ["india portal", "government", "citizen"], verified: true, popular: true, trending: false },
{ id: 61, name: "MyGov", url: "https://www.mygov.in", category: "government", sub: "Portals & Services", desc: "Citizen engagement platform for government initiatives, discussions, and public participation.", tags: ["mygov", "citizen", "government"], verified: true, popular: true, trending: false },
{ id: 62, name: "Open Government Data", url: "https://data.gov.in", category: "government", sub: "Portals & Services", desc: "Official portal providing open datasets published by Government of India departments.", tags: ["open data", "data.gov.in", "datasets"], verified: true, popular: false, trending: false },
{ id: 63, name: "GeM", url: "https://gem.gov.in", category: "government", sub: "Portals & Services", desc: "Government e-Marketplace for procurement of goods and services by government organizations.", tags: ["gem", "procurement", "marketplace"], verified: true, popular: true, trending: false },
{ id: 64, name: "PM India", url: "https://www.pmindia.gov.in", category: "government", sub: "Portals & Services", desc: "Official website of the Prime Minister of India with speeches, updates, and initiatives.", tags: ["pm india", "prime minister", "government"], verified: true, popular: true, trending: false },
{ id: 65, name: "National Scholarship Portal", url: "https://scholarships.gov.in", category: "government", sub: "Portals & Services", desc: "Official portal for scholarship applications, verification, and student financial assistance.", tags: ["scholarship", "students", "education"], verified: true, popular: true, trending: false },
{ id: 66, name: "Startup India", url: "https://www.startupindia.gov.in", category: "government", sub: "Portals & Services", desc: "Official portal supporting startups with recognition, funding, and government initiatives.", tags: ["startup india", "startup", "entrepreneur"], verified: true, popular: true, trending: false },
{ id: 67, name: "Digital India", url: "https://digitalindia.gov.in", category: "government", sub: "Portals & Services", desc: "Official portal promoting digital governance, digital services, and technology initiatives.", tags: ["digital india", "technology", "digital services"], verified: true, popular: true, trending: false },
{ id: 68, name: "Bharat BillPay", url: "https://www.bharatbillpay.com", category: "government", sub: "Portals & Services", desc: "Integrated bill payment platform for electricity, water, gas, telecom, and other utility bills.", tags: ["bill payment", "bbps", "bharat billpay"], verified: true, popular: true, trending: false },
{ id: 69, name: "RTI Online", url: "https://rtionline.gov.in", category: "government", sub: "Portals & Services", desc: "Official portal to file and track Right to Information (RTI) applications online.", tags: ["rti", "information", "transparency"], verified: true, popular: true, trending: false },

  // ---------------- BANKING & FINANCE ----------------
  { id:21, name:"RBI", url:"https://www.rbi.org.in", category:"finance", sub:"Regulatory", desc:"Reserve Bank of India — monetary policy, regulations and financial literacy resources.", tags:["banking","regulator"], verified:true },
  { id:22, name:"State Bank of India", url:"https://www.onlinesbi.sbi", category:"finance", sub:"Banking", desc:"Net banking portal for India's largest public sector bank.", tags:["bank","netbanking"], verified:true, popular:true },
  { id:23, name:"HDFC Bank", url:"https://www.hdfcbank.com", category:"finance", sub:"Banking", desc:"Retail and corporate banking services from one of India's largest private banks.", tags:["bank","netbanking"], verified:true, popular:true },
  { id:24, name:"ICICI Bank", url:"https://www.icicibank.com", category:"finance", sub:"Banking", desc:"Banking, loans, cards and investment services.", tags:["bank","loans"], verified:true },
  { id:25, name:"Axis Bank", url:"https://www.axisbank.com", category:"finance", sub:"Banking", desc:"Personal and business banking services across India.", tags:["bank"], verified:true },
  { id:26, name:"NSE India", url:"https://www.nseindia.com", category:"finance", sub:"Investments", desc:"National Stock Exchange — live market data, indices and listed company info.", tags:["stocks","markets"], verified:true },
  { id:27, name:"BSE India", url:"https://www.bseindia.com", category:"finance", sub:"Investments", desc:"Asia's oldest stock exchange, offering market data and corporate announcements.", tags:["stocks","markets"], verified:true },
  { id:28, name:"Zerodha", url:"https://zerodha.com", category:"finance", sub:"Investments", desc:"India's largest stock broker for equity, mutual fund and derivatives trading.", tags:["trading","investing"], verified:true, popular:true, trending:true },
  { id:29, name:"Groww", url:"https://groww.in", category:"finance", sub:"Investments", desc:"Investing app for stocks, mutual funds, IPOs and digital gold.", tags:["investing","mutual funds"], verified:true, popular:true },
  { id:30, name:"Paytm", url:"https://paytm.com", category:"finance", sub:"Payments", desc:"Digital payments, recharges, bill payments and UPI transfers.", tags:["upi","payments"], verified:true, popular:true, trending:true },
  { id:31, name:"PhonePe", url:"https://www.phonepe.com", category:"finance", sub:"Payments", desc:"UPI payments, recharges, insurance and investment in one app.", tags:["upi","payments"], verified:true, popular:true, trending:true },
  { id:32, name:"Google Pay", url:"https://pay.google.com/intl/en_in/about/", category:"finance", sub:"Payments", desc:"UPI-based payments app for quick money transfers and bill payments.", tags:["upi","payments"], verified:true, popular:true },
  { id:33, name:"Policybazaar", url:"https://www.policybazaar.com", category:"finance", sub:"Insurance", desc:"Compare and buy health, life, motor and travel insurance policies online.", tags:["insurance","compare"], verified:true, popular:true },
  { id:34, name:"CAMS KRA", url:"https://www.camsonline.com", category:"finance", sub:"Investments", desc:"Mutual fund transaction and registry services for investors.", tags:["mutual funds","kyc"], verified:true },
  { id:35, name:"CoinDCX", url:"https://coindcx.com", category:"finance", sub:"Cryptocurrency", desc:"Indian cryptocurrency exchange for buying, selling and trading digital assets.", tags:["crypto","exchange"], verified:true },
  // ---------------- SHOPPING ----------------
  { id:36, name:"Amazon India", url:"https://www.amazon.in", category:"shopping", sub:"Marketplace", desc:"Online marketplace for electronics, fashion, groceries and nearly everything else.", tags:["ecommerce","marketplace"], verified:true, popular:true, trending:true },
  { id:37, name:"Flipkart", url:"https://www.flipkart.com", category:"shopping", sub:"Marketplace", desc:"India's homegrown ecommerce giant for electronics, fashion and home goods.", tags:["ecommerce","marketplace"], verified:true, popular:true, trending:true },
  { id:38, name:"Myntra", url:"https://www.myntra.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Fashion and lifestyle shopping for clothing, footwear and accessories.", tags:["fashion","clothing"], verified:true, popular:true },
  { id:39, name:"Ajio", url:"https://www.ajio.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Reliance's fashion ecommerce platform with curated brand collections.", tags:["fashion","clothing"], verified:true },
  { id:40, name:"Nykaa", url:"https://www.nykaa.com", category:"shopping", sub:"Beauty & Personal Care", desc:"Beauty, wellness and personal care products marketplace.", tags:["beauty","cosmetics"], verified:true, popular:true },
  { id:41, name:"Meesho", url:"https://www.meesho.com", category:"shopping", sub:"Marketplace", desc:"Budget-friendly social commerce marketplace for reselling and shopping.", tags:["ecommerce","budget"], verified:true, popular:true },
  { id:42, name:"BigBasket", url:"https://www.bigbasket.com", category:"shopping", sub:"Grocery & Quick Commerce", desc:"Online grocery delivery for daily essentials, fresh produce and staples.", tags:["grocery","delivery"], verified:true, popular:true },
  { id:43, name:"Blinkit", url:"https://blinkit.com", category:"shopping", sub:"Grocery & Quick Commerce", desc:"10-minute grocery and essentials delivery service.", tags:["grocery","quick commerce"], verified:true, popular:true, trending:true },
  { id:44, name:"Zepto", url:"https://www.zeptonow.com", category:"shopping", sub:"Grocery & Quick Commerce", desc:"Quick-commerce app delivering groceries in minutes.", tags:["grocery","quick commerce"], verified:true, trending:true },
  { id:45, name:"Snapdeal", url:"https://www.snapdeal.com", category:"shopping", sub:"Marketplace", desc:"Value-focused online shopping marketplace across categories.", tags:["ecommerce"], verified:true },
  { id:46, name:"Tata CLiQ", url:"https://www.tatacliq.com", category:"shopping", sub:"Marketplace", desc:"Multi-brand online shopping platform for fashion and electronics.", tags:["ecommerce","fashion"], verified:true },
  { id:47, name:"IKEA India", url:"https://www.ikea.com/in/en/", category:"shopping", sub:"Home & Furniture", desc:"Furniture and home furnishing store with online shopping and delivery.", tags:["furniture","home"], verified:true },
  // ---------------- EDUCATION ----------------
  { id:48, name:"BYJU'S", url:"https://byjus.com", category:"education", sub:"School Learning", desc:"Online learning platform for school students and competitive exam prep.", tags:["learning","school"], verified:true, popular:true },
  { id:49, name:"Unacademy", url:"https://unacademy.com", category:"education", sub:"Exam Preparation", desc:"Live classes and courses for competitive exams and skill learning.", tags:["exam prep","live classes"], verified:true, popular:true },
  { id:50, name:"Vedantu", url:"https://www.vedantu.com", category:"education", sub:"School Learning", desc:"Live online tutoring for school subjects and board exam preparation.", tags:["tutoring","school"], verified:true },
  { id:51, name:"NCERT", url:"https://ncert.nic.in", category:"education", sub:"School Learning", desc:"Official source for NCERT textbooks and curriculum resources.", tags:["textbooks","curriculum"], verified:true, popular:true },
  { id:52, name:"UGC", url:"https://www.ugc.gov.in", category:"education", sub:"Higher Education", desc:"University Grants Commission — regulates higher education standards in India.", tags:["higher education","regulator"], verified:true },
  { id:53, name:"SWAYAM", url:"https://swayam.gov.in", category:"education", sub:"Free Courses & MOOCs", desc:"Government platform offering free online courses from school to postgraduate level.", tags:["free courses","moocs"], verified:true, popular:true },
  { id:54, name:"NPTEL", url:"https://nptel.ac.in", category:"education", sub:"Free Courses & MOOCs", desc:"Free engineering and science video courses from IITs and IISc.", tags:["engineering","iit"], verified:true, popular:true },
  { id:55, name:"National Scholarship Portal", url:"https://scholarships.gov.in", category:"education", sub:"Scholarships", desc:"Apply for central and state government scholarships in one place.", tags:["scholarships","students"], verified:true, popular:true },
  { id:56, name:"Khan Academy", url:"https://www.khanacademy.org", category:"education", sub:"Free Courses & MOOCs", desc:"Free world-class education across math, science and more.", tags:["free courses","global"], verified:true },
  { id:57, name:"Coursera", url:"https://www.coursera.org", category:"education", sub:"Free Courses & MOOCs", desc:"Online courses and degrees from top universities and companies worldwide.", tags:["moocs","certificates"], verified:true, popular:true },
  { id:58, name:"Physics Wallah", url:"https://www.pw.live", category:"education", sub:"Exam Preparation", desc:"Affordable online coaching for JEE, NEET and school exams.", tags:["exam prep","affordable"], verified:true, trending:true },
  // ---------------- JOBS & CAREERS ----------------
  { id:59, name:"Naukri.com", url:"https://www.naukri.com", category:"jobs", sub:"Job Portals", desc:"India's leading job search portal across every industry and experience level.", tags:["jobs","recruitment"], verified:true, popular:true, trending:true },
  { id:60, name:"LinkedIn", url:"https://www.linkedin.com", category:"jobs", sub:"Professional Networking", desc:"Professional networking platform for jobs, hiring and career growth.", tags:["networking","jobs"], verified:true, popular:true },
  { id:61, name:"Internshala", url:"https://internshala.com", category:"jobs", sub:"Internships", desc:"Internships and fresher jobs for students across India.", tags:["internships","students"], verified:true, popular:true },
  { id:62, name:"Indeed India", url:"https://in.indeed.com", category:"jobs", sub:"Job Portals", desc:"Global job search engine aggregating listings from across the web.", tags:["jobs","search"], verified:true },
  { id:63, name:"Sarkari Result", url:"https://www.sarkariresult.com", category:"jobs", sub:"Government Jobs", desc:"Government job notifications, admit cards and exam results.", tags:["government jobs","exam results"], verified:true, popular:true },
  { id:64, name:"SSC Online", url:"https://ssc.nic.in", category:"jobs", sub:"Government Jobs", desc:"Staff Selection Commission portal for government recruitment exams.", tags:["government jobs","exams"], verified:true },
  { id:65, name:"Freshersworld", url:"https://www.freshersworld.com", category:"jobs", sub:"Job Portals", desc:"Job portal focused on entry-level and fresher opportunities.", tags:["freshers","entry level"], verified:true },
  { id:66, name:"Upwork", url:"https://www.upwork.com", category:"jobs", sub:"Freelancing", desc:"Global freelancing marketplace for remote work across skills.", tags:["freelancing","remote"], verified:true },
  // ---------------- TRAVEL & TRANSPORT ----------------
  { id:67, name:"MakeMyTrip", url:"https://www.makemytrip.com", category:"travel", sub:"Flights & Hotels", desc:"Flights, hotels, trains and holiday packages booking platform.", tags:["flights","hotels"], verified:true, popular:true, trending:true },
  { id:68, name:"Goibibo", url:"https://www.goibibo.com", category:"travel", sub:"Flights & Hotels", desc:"Book flights, hotels and buses at competitive prices.", tags:["flights","hotels"], verified:true, popular:true },
  { id:69, name:"redBus", url:"https://www.redbus.in", category:"travel", sub:"Trains & Buses", desc:"India's largest online bus ticket booking platform.", tags:["bus","tickets"], verified:true, popular:true },
  { id:70, name:"ixigo", url:"https://www.ixigo.com", category:"travel", sub:"Trains & Buses", desc:"Flight, train and bus booking with real-time travel assistance.", tags:["flights","trains"], verified:true },
  { id:71, name:"OYO Rooms", url:"https://www.oyorooms.com", category:"travel", sub:"Flights & Hotels", desc:"Budget hotel booking chain with standardized stays across India.", tags:["hotels","budget"], verified:true, popular:true },
  { id:72, name:"Air India", url:"https://www.airindia.com", category:"travel", sub:"Airlines", desc:"National carrier of India for domestic and international flight booking.", tags:["airline","flights"], verified:true },
  { id:73, name:"IndiGo", url:"https://www.goindigo.in", category:"travel", sub:"Airlines", desc:"India's largest airline by passengers carried, for flight bookings.", tags:["airline","flights"], verified:true, popular:true },
  { id:74, name:"Google Maps", url:"https://maps.google.com", category:"travel", sub:"Navigation & Maps", desc:"Navigation, live traffic and place discovery across India and the world.", tags:["maps","navigation"], verified:true, popular:true },
  { id:75, name:"Delhi Metro Rail (DMRC)", url:"https://www.delhimetrorail.com", category:"travel", sub:"Local Transit", desc:"Route maps, fares and timings for the Delhi Metro network.", tags:["metro","transit"], verified:true },
  { id:76, name:"Incredible India", url:"https://www.incredibleindia.org", category:"travel", sub:"Tourism", desc:"Official tourism portal showcasing destinations across India.", tags:["tourism","destinations"], verified:true },
  // ---------------- ENTERTAINMENT ----------------
  { id:77, name:"JioHotstar", url:"https://www.hotstar.com", category:"entertainment", sub:"Video Streaming", desc:"Streaming platform for movies, shows, live sports and cricket.", tags:["streaming","sports"], verified:true, popular:true, trending:true },
  { id:78, name:"Netflix", url:"https://www.netflix.com", category:"entertainment", sub:"Video Streaming", desc:"Global streaming service for movies, series and originals.", tags:["streaming","movies"], verified:true, popular:true },
  { id:79, name:"Amazon Prime Video", url:"https://www.primevideo.com", category:"entertainment", sub:"Video Streaming", desc:"Streaming service bundled with Amazon Prime for movies and shows.", tags:["streaming","movies"], verified:true, popular:true },
  { id:80, name:"Spotify", url:"https://www.spotify.com", category:"entertainment", sub:"Music & Podcasts", desc:"Music and podcast streaming with personalized playlists.", tags:["music","podcasts"], verified:true, popular:true },
  { id:81, name:"JioSaavn", url:"https://www.jiosaavn.com", category:"entertainment", sub:"Music & Podcasts", desc:"Music streaming platform with a large Indian and Bollywood catalogue.", tags:["music","bollywood"], verified:true, popular:true },
  { id:82, name:"Gaana", url:"https://gaana.com", category:"entertainment", sub:"Music & Podcasts", desc:"Indian music streaming service across languages and genres.", tags:["music"], verified:true },
  { id:83, name:"BookMyShow", url:"https://in.bookmyshow.com", category:"entertainment", sub:"Live Events & Tickets", desc:"Movie tickets, events and live show bookings across Indian cities.", tags:["movie tickets","events"], verified:true, popular:true, trending:true },
  { id:84, name:"YouTube", url:"https://www.youtube.com", category:"entertainment", sub:"Video Sharing", desc:"Video sharing platform for entertainment, learning and creators.", tags:["video","streaming"], verified:true, popular:true },
  // ---------------- NEWS & MEDIA ----------------
  { id:85, name:"NDTV", url:"https://www.ndtv.com", category:"news", sub:"National News", desc:"National news, business and lifestyle coverage.", tags:["news","national"], verified:true, popular:true },
  { id:86, name:"The Times of India", url:"https://timesofindia.indiatimes.com", category:"news", sub:"National News", desc:"India's widely read English daily, covering national and world news.", tags:["news","national"], verified:true, popular:true },
  { id:87, name:"The Hindu", url:"https://www.thehindu.com", category:"news", sub:"National News", desc:"National newspaper known for in-depth political and policy coverage.", tags:["news","national"], verified:true },
  { id:88, name:"Indian Express", url:"https://indianexpress.com", category:"news", sub:"National News", desc:"National daily covering politics, business and current affairs.", tags:["news","national"], verified:true },
  { id:89, name:"News18", url:"https://www.news18.com", category:"news", sub:"National News", desc:"Multi-language news network covering India and the world.", tags:["news","regional"], verified:true },
  { id:90, name:"Moneycontrol", url:"https://www.moneycontrol.com", category:"news", sub:"Business & Markets", desc:"Business and financial news, stock quotes and market analysis.", tags:["business","markets"], verified:true, popular:true },
  { id:91, name:"ESPNcricinfo", url:"https://www.espncricinfo.com", category:"news", sub:"Sports News", desc:"Live cricket scores, news and analysis from around the world.", tags:["cricket","sports"], verified:true, popular:true },
  // ---------------- HEALTH ----------------
  { id:92, name:"Practo", url:"https://www.practo.com", category:"health", sub:"Doctor Consultation", desc:"Find doctors, book appointments and consult online.", tags:["doctors","appointments"], verified:true, popular:true },
  { id:93, name:"1mg", url:"https://www.1mg.com", category:"health", sub:"Pharmacy & Medicine", desc:"Order medicines online and book lab tests with home sample collection.", tags:["medicine","pharmacy"], verified:true, popular:true, trending:true },
  { id:94, name:"PharmEasy", url:"https://pharmeasy.in", category:"health", sub:"Pharmacy & Medicine", desc:"Online pharmacy for medicines, healthcare products and diagnostics.", tags:["medicine","pharmacy"], verified:true, popular:true },
  { id:95, name:"Apollo 24|7", url:"https://www.apollo247.com", category:"health", sub:"Doctor Consultation", desc:"Online doctor consultations, medicine delivery and diagnostic tests.", tags:["doctors","medicine"], verified:true },
  { id:96, name:"AIIMS Delhi", url:"https://www.aiims.edu", category:"health", sub:"Hospitals & Research", desc:"Premier government medical institute for treatment, research and education.", tags:["hospital","research"], verified:true },
  { id:97, name:"National Health Portal", url:"https://www.nhp.gov.in", category:"health", sub:"Government Health Info", desc:"Government portal for verified health information and services.", tags:["health info","government"], verified:true },
  // ---------------- FOOD & GROCERY ----------------
  { id:98, name:"Swiggy", url:"https://www.swiggy.com", category:"food", sub:"Food Delivery", desc:"Food delivery, quick grocery delivery and dining discovery.", tags:["food delivery","grocery"], verified:true, popular:true, trending:true },
  { id:99, name:"Zomato", url:"https://www.zomato.com", category:"food", sub:"Food Delivery", desc:"Restaurant discovery, reviews and online food delivery.", tags:["food delivery","restaurants"], verified:true, popular:true, trending:true },
  { id:100, name:"EatSure", url:"https://www.eatsure.com", category:"food", sub:"Food Delivery", desc:"Cloud-kitchen food delivery brand with curated meal options.", tags:["food delivery"], verified:true },
  { id:101, name:"Licious", url:"https://www.licious.in", category:"food", sub:"Specialty Food", desc:"Fresh meat and seafood delivery across major Indian cities.", tags:["meat","grocery"], verified:true },
  // ---------------- AI TOOLS ----------------
  { id:102, name:"Claude", url:"https://claude.ai", category:"ai", sub:"AI Assistants", desc:"AI assistant by Anthropic for writing, coding, research and analysis.", tags:["ai assistant","anthropic"], verified:true, popular:true, trending:true },
  { id:103, name:"ChatGPT", url:"https://chatgpt.com", category:"ai", sub:"AI Assistants", desc:"OpenAI's conversational AI assistant for a wide range of tasks.", tags:["ai assistant","openai"], verified:true, popular:true, trending:true },
  { id:104, name:"Gemini", url:"https://gemini.google.com", category:"ai", sub:"AI Assistants", desc:"Google's AI assistant integrated with search and workspace tools.", tags:["ai assistant","google"], verified:true, popular:true },
  { id:105, name:"Perplexity", url:"https://www.perplexity.ai", category:"ai", sub:"AI Search", desc:"AI-powered answer engine that cites sources for its responses.", tags:["ai search","research"], verified:true, popular:true },
  { id:106, name:"Krutrim", url:"https://www.krutrim.ai", category:"ai", sub:"Indian AI", desc:"Indian AI platform building multilingual models for Indian languages.", tags:["ai assistant","indian"], verified:true, trending:true },
  { id:107, name:"Microsoft Copilot", url:"https://copilot.microsoft.com", category:"ai", sub:"AI Assistants", desc:"AI assistant integrated across Microsoft's productivity apps.", tags:["ai assistant","microsoft"], verified:true },
  // ---------------- SOCIAL & MESSAGING ----------------
  { id:108, name:"WhatsApp", url:"https://www.whatsapp.com", category:"social", sub:"Messaging", desc:"India's most widely used messaging app for chat, voice and video calls.", tags:["messaging","calls"], verified:true, popular:true, trending:true },
  { id:109, name:"Instagram", url:"https://www.instagram.com", category:"social", sub:"Social Networking", desc:"Photo and video sharing social network.", tags:["photos","video"], verified:true, popular:true },
  { id:110, name:"Facebook", url:"https://www.facebook.com", category:"social", sub:"Social Networking", desc:"Social networking platform for connecting with friends and communities.", tags:["social network"], verified:true },
  { id:111, name:"X (Twitter)", url:"https://x.com", category:"social", sub:"Social Networking", desc:"Real-time public conversation and news platform.", tags:["microblogging","news"], verified:true, popular:true },
  { id:112, name:"Telegram", url:"https://telegram.org", category:"social", sub:"Messaging", desc:"Cloud-based messaging app known for large groups and channels.", tags:["messaging","channels"], verified:true },
  { id:113, name:"ShareChat", url:"https://sharechat.com", category:"social", sub:"Regional Social", desc:"Indian social media platform for regional-language content.", tags:["regional","social network"], verified:true },
  // ---------------- REAL ESTATE ----------------
  { id:114, name:"99acres", url:"https://www.99acres.com", category:"realestate", sub:"Property Listings", desc:"Property listings for buying, selling and renting homes across India.", tags:["property","rent"], verified:true, popular:true },
  { id:115, name:"MagicBricks", url:"https://www.magicbricks.com", category:"realestate", sub:"Property Listings", desc:"Real estate portal for residential and commercial property search.", tags:["property","buy"], verified:true, popular:true },
  { id:116, name:"Housing.com", url:"https://housing.com", category:"realestate", sub:"Property Listings", desc:"Property search platform with verified listings and virtual tours.", tags:["property","rent"], verified:true },
  { id:117, name:"NoBroker", url:"https://www.nobroker.in", category:"realestate", sub:"Brokerage-Free", desc:"Brokerage-free platform to rent, buy or sell property directly.", tags:["property","no brokerage"], verified:true, trending:true },
  // ---------------- UTILITIES & BILLS ----------------
  { id:118, name:"BillDesk", url:"https://www.billdesk.com", category:"utilities", sub:"Bill Payments", desc:"Online bill payment platform for utilities, insurance and more.", tags:["bill payment"], verified:true },
  { id:119, name:"Airtel Thanks", url:"https://www.airtel.in", category:"utilities", sub:"Telecom Recharge", desc:"Recharge, bill payment and account management for Airtel services.", tags:["recharge","telecom"], verified:true, popular:true },
  { id:120, name:"Jio", url:"https://www.jio.com", category:"utilities", sub:"Telecom Recharge", desc:"Recharge plans and account management for Jio mobile and broadband.", tags:["recharge","telecom"], verified:true, popular:true },
  { id:121, name:"Vi (Vodafone Idea)", url:"https://www.myvi.in", category:"utilities", sub:"Telecom Recharge", desc:"Recharge and manage Vi prepaid and postpaid mobile connections.", tags:["recharge","telecom"], verified:true },
  // ---------------- PRODUCTIVITY & DEV ----------------
  { id:122, name:"GitHub", url:"https://github.com", category:"productivity", sub:"Code & Dev", desc:"Code hosting platform for version control and collaboration.", tags:["code","git"], verified:true, popular:true },
  { id:123, name:"Google Drive", url:"https://drive.google.com", category:"productivity", sub:"Cloud Storage", desc:"Cloud storage and file sharing integrated with Google Workspace.", tags:["cloud storage","files"], verified:true, popular:true },
  { id:124, name:"Notion", url:"https://www.notion.com", category:"productivity", sub:"Docs & Notes", desc:"All-in-one workspace for notes, docs, wikis and project tracking.", tags:["notes","docs"], verified:true, popular:true },
  { id:125, name:"Canva", url:"https://www.canva.com", category:"productivity", sub:"Design Tools", desc:"Drag-and-drop design tool for graphics, presentations and social posts.", tags:["design","graphics"], verified:true, popular:true, trending:true },
  { id:126, name:"iLovePDF", url:"https://www.ilovepdf.com", category:"productivity", sub:"PDF Tools", desc:"Free online tools to merge, split, compress and convert PDFs.", tags:["pdf","tools"], verified:true, popular:true },
  { id:127, name:"Zoom", url:"https://zoom.us", category:"productivity", sub:"Video Conferencing", desc:"Video conferencing platform for meetings, webinars and classes.", tags:["video calls","meetings"], verified:true, popular:true },
  { id:128, name:"Vercel", url:"https://vercel.com", category:"productivity", sub:"Hosting & Deployment", desc:"Cloud platform for deploying and hosting frontend web applications.", tags:["hosting","deployment"], verified:true },
  { id:129, name:"Namecheap", url:"https://www.namecheap.com", category:"productivity", sub:"Hosting & Deployment", desc:"Domain registration and web hosting services.", tags:["domains","hosting"], verified:true },
  // ---------------- GOVERNMENT ----------------
  { id:130, name:"MCA (Ministry of Corporate Affairs)", url:"https://www.mca.gov.in", category:"government", sub:"Portals & Services", desc:"Company registration, filings and corporate compliance services for businesses in India.", tags:["business","compliance"], verified:true },
  { id:131, name:"PM-KISAN", url:"https://pmkisan.gov.in", category:"government", sub:"Employment & Welfare", desc:"Direct income support scheme portal for farmer registration and benefit status.", tags:["farmers","welfare"], verified:true },
  { id:132, name:"National Career Service", url:"https://www.ncs.gov.in", category:"government", sub:"Employment & Welfare", desc:"Government job-matching platform connecting job seekers with employers and training.", tags:["jobs","career"], verified:true },
  { id:133, name:"Jan Aushadhi", url:"https://janaushadhi.gov.in", category:"government", sub:"Health & Safety", desc:"Locate government-run stores selling affordable generic medicines.", tags:["medicine","affordable"], verified:true },
  { id:134, name:"MSME / Udyam Registration", url:"https://www.msme.gov.in", category:"government", sub:"Portals & Services", desc:"Registration and support services for micro, small and medium enterprises.", tags:["msme","business"], verified:true },
  // ---------------- BANKING & FINANCE ----------------
  { id:135, name:"Kotak Mahindra Bank", url:"https://www.kotak.com", category:"finance", sub:"Banking", desc:"Retail and corporate banking, loans and net banking services.", tags:["bank","netbanking"], verified:true },
  { id:136, name:"Yes Bank", url:"https://www.yesbank.in", category:"finance", sub:"Banking", desc:"Digital banking, loans and corporate financial services.", tags:["bank"], verified:true },
  { id:137, name:"Punjab National Bank", url:"https://www.pnbindia.in", category:"finance", sub:"Banking", desc:"Net banking and financial services from a major public sector bank.", tags:["bank","netbanking"], verified:true },
  { id:138, name:"Bank of Baroda", url:"https://www.bankofbaroda.in", category:"finance", sub:"Banking", desc:"Retail and corporate banking services with wide branch network across India.", tags:["bank"], verified:true },
  { id:139, name:"IDFC FIRST Bank", url:"https://www.idfcfirstbank.com", category:"finance", sub:"Banking", desc:"Digital-first private bank offering accounts, loans and cards.", tags:["bank","digital"], verified:true },
  { id:140, name:"Upstox", url:"https://upstox.com", category:"finance", sub:"Investments", desc:"Discount broking platform for stocks, mutual funds and derivatives.", tags:["trading","investing"], verified:true, popular:true },
  { id:141, name:"Angel One", url:"https://www.angelone.in", category:"finance", sub:"Investments", desc:"Full-service stockbroker offering trading, investing and advisory tools.", tags:["trading","investing"], verified:true, popular:true },
  { id:142, name:"ICICI Direct", url:"https://www.icicidirect.com", category:"finance", sub:"Investments", desc:"Online trading and investment platform from ICICI Securities.", tags:["trading","investing"], verified:true },
  { id:143, name:"MF Central", url:"https://www.mfcentral.com", category:"finance", sub:"Investments", desc:"Centralized mutual fund transaction and portfolio servicing platform.", tags:["mutual funds"], verified:true },
  { id:144, name:"CRED", url:"https://cred.club", category:"finance", sub:"Payments", desc:"Credit card bill payments and rewards platform for members.", tags:["credit card","rewards"], verified:true, popular:true },
  { id:145, name:"BharatPe", url:"https://bharatpe.com", category:"finance", sub:"Payments", desc:"UPI payments and merchant lending platform for small businesses.", tags:["upi","merchants"], verified:true },
  { id:146, name:"Razorpay", url:"https://razorpay.com", category:"finance", sub:"Payments", desc:"Payment gateway and business banking platform for Indian companies.", tags:["payment gateway","business"], verified:true, popular:true },
  { id:147, name:"LIC India", url:"https://licindia.in", category:"finance", sub:"Insurance", desc:"Life Insurance Corporation of India — policies, premium payment and claims.", tags:["life insurance","government"], verified:true, popular:true },
  { id:148, name:"Acko", url:"https://www.acko.com", category:"finance", sub:"Insurance", desc:"Digital-first insurer for car, bike and health insurance policies.", tags:["insurance","digital"], verified:true },
  { id:149, name:"Digit Insurance", url:"https://www.godigit.com", category:"finance", sub:"Insurance", desc:"General insurance provider for motor, health and travel coverage.", tags:["insurance"], verified:true },
  { id:150, name:"ClearTax", url:"https://cleartax.in", category:"finance", sub:"Tax Services", desc:"Online income tax filing, GST and investment platform.", tags:["tax","filing"], verified:true, popular:true },
  { id:151, name:"TaxBuddy", url:"https://www.taxbuddy.com", category:"finance", sub:"Tax Services", desc:"Assisted income tax return filing and tax planning services.", tags:["tax","filing"], verified:true },
  { id:152, name:"WazirX", url:"https://wazirx.com", category:"finance", sub:"Cryptocurrency", desc:"Cryptocurrency exchange for trading Bitcoin and other digital assets.", tags:["crypto","exchange"], verified:true },
  { id:153, name:"SEBI", url:"https://www.sebi.gov.in", category:"finance", sub:"Regulatory", desc:"Securities and Exchange Board of India — capital markets regulator.", tags:["regulator","markets"], verified:true },
  { id:154, name:"IRDAI", url:"https://irdai.gov.in", category:"finance", sub:"Regulatory", desc:"Insurance Regulatory and Development Authority of India.", tags:["regulator","insurance"], verified:true },
  { id:155, name:"SBI Life Insurance", url:"https://www.sbilife.co.in", category:"finance", sub:"Insurance", desc:"Life insurance policies, premium payment and claim services.", tags:["life insurance"], verified:true },
  { id:156, name:"Tata AIA Life Insurance", url:"https://www.tataaia.com", category:"finance", sub:"Insurance", desc:"Life insurance plans, savings and protection products.", tags:["life insurance"], verified:true },
  { id:157, name:"Bajaj Finserv", url:"https://www.bajajfinserv.in", category:"finance", sub:"Loans & Lending", desc:"Personal loans, EMI cards and consumer financing services.", tags:["loans","emi"], verified:true, popular:true },
  { id:158, name:"KreditBee", url:"https://www.kreditbee.in", category:"finance", sub:"Loans & Lending", desc:"Instant personal loan app for salaried and self-employed individuals.", tags:["loans","instant credit"], verified:true },
  { id:159, name:"Paisabazaar", url:"https://www.paisabazaar.com", category:"finance", sub:"Loans & Lending", desc:"Compare and apply for loans, credit cards and credit scores.", tags:["loans","credit score"], verified:true, popular:true },
  // ---------------- SHOPPING ----------------
  { id:160, name:"Croma", url:"https://www.croma.com", category:"shopping", sub:"Marketplace", desc:"Electronics and appliance retail chain with online shopping.", tags:["electronics","appliances"], verified:true },
  { id:161, name:"Reliance Digital", url:"https://www.reliancedigital.in", category:"shopping", sub:"Marketplace", desc:"Electronics retailer offering gadgets, appliances and accessories.", tags:["electronics"], verified:true },
  { id:162, name:"Lenskart", url:"https://www.lenskart.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Eyewear brand for glasses, sunglasses and contact lenses.", tags:["eyewear","glasses"], verified:true, popular:true },
  { id:163, name:"FirstCry", url:"https://www.firstcry.com", category:"shopping", sub:"Marketplace", desc:"Online store for baby, kids and maternity products.", tags:["kids","baby"], verified:true, popular:true },
  { id:164, name:"Pepperfry", url:"https://www.pepperfry.com", category:"shopping", sub:"Home & Furniture", desc:"Furniture and home decor marketplace with delivery across India.", tags:["furniture","decor"], verified:true, popular:true },
  { id:165, name:"Purplle", url:"https://www.purplle.com", category:"shopping", sub:"Beauty & Personal Care", desc:"Beauty and cosmetics marketplace for skincare and makeup products.", tags:["beauty","cosmetics"], verified:true },
  { id:166, name:"Shopsy", url:"https://www.shopsy.in", category:"shopping", sub:"Marketplace", desc:"Flipkart's budget-focused shopping app for value fashion and essentials.", tags:["ecommerce","budget"], verified:true },
  { id:167, name:"JioMart", url:"https://www.jiomart.com", category:"shopping", sub:"Grocery & Quick Commerce", desc:"Online grocery and daily essentials delivery from Reliance Retail.", tags:["grocery","delivery"], verified:true, popular:true },
  { id:168, name:"Dunzo", url:"https://www.dunzo.com", category:"shopping", sub:"Grocery & Quick Commerce", desc:"On-demand delivery service for groceries and daily errands.", tags:["delivery","errands"], verified:true },
  { id:169, name:"H&M India", url:"https://www2.hm.com/en_in", category:"shopping", sub:"Fashion & Lifestyle", desc:"Global fashion retailer for clothing and accessories.", tags:["fashion","clothing"], verified:true },
  { id:170, name:"Decathlon India", url:"https://www.decathlon.in", category:"shopping", sub:"Fashion & Lifestyle", desc:"Sports and fitness equipment, apparel and accessories retailer.", tags:["sports","fitness gear"], verified:true, popular:true },
  { id:171, name:"Urban Ladder", url:"https://www.urbanladder.com", category:"shopping", sub:"Home & Furniture", desc:"Furniture and home interior products with design services.", tags:["furniture","interiors"], verified:true },
  { id:172, name:"Fabindia", url:"https://www.fabindia.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Ethnic clothing, home furnishings and organic products retailer.", tags:["ethnic wear","handmade"], verified:true },
  { id:173, name:"Shoppers Stop", url:"https://www.shoppersstop.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Department store chain for fashion, beauty and accessories.", tags:["fashion","department store"], verified:true },
  { id:174, name:"Lifestyle Stores", url:"https://www.lifestylestores.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Fashion and lifestyle retail chain for apparel and accessories.", tags:["fashion","retail"], verified:true },
  { id:175, name:"Bewakoof", url:"https://www.bewakoof.com", category:"shopping", sub:"Fashion & Lifestyle", desc:"Youth-focused streetwear and casual fashion brand.", tags:["streetwear","casual"], verified:true },
  { id:176, name:"Vijay Sales", url:"https://www.vijaysales.com", category:"shopping", sub:"Marketplace", desc:"Consumer electronics and home appliance retail chain.", tags:["electronics","appliances"], verified:true },
  { id:177, name:"Swiggy Instamart", url:"https://www.swiggy.com/instamart", category:"shopping", sub:"Grocery & Quick Commerce", desc:"Quick-commerce grocery delivery service from Swiggy.", tags:["grocery","quick commerce"], verified:true, popular:true, trending:true },
  // ---------------- EDUCATION ----------------
  { id:178, name:"Toppr", url:"https://www.toppr.com", category:"education", sub:"Exam Preparation", desc:"Adaptive learning app for school and competitive exam preparation.", tags:["exam prep","adaptive learning"], verified:true },
  { id:179, name:"Testbook", url:"https://testbook.com", category:"education", sub:"Exam Preparation", desc:"Mock tests and courses for government and competitive exams.", tags:["exam prep","mock tests"], verified:true, popular:true },
  { id:180, name:"Chegg India", url:"https://www.chegg.com", category:"education", sub:"Higher Education", desc:"Study help, textbook solutions and homework assistance for students.", tags:["study help","textbooks"], verified:true },
  { id:181, name:"upGrad", url:"https://www.upgrad.com", category:"education", sub:"Higher Education", desc:"Online degree and certification programs with top universities.", tags:["online degrees","upskilling"], verified:true, popular:true },
  { id:182, name:"Simplilearn", url:"https://www.simplilearn.com", category:"education", sub:"Higher Education", desc:"Professional certification courses in tech, data and management.", tags:["certification","upskilling"], verified:true },
  { id:183, name:"Great Learning", url:"https://www.mygreatlearning.com", category:"education", sub:"Higher Education", desc:"Online and blended learning programs in data science, AI and business.", tags:["upskilling","certification"], verified:true },
  { id:184, name:"edX", url:"https://www.edx.org", category:"education", sub:"Free Courses & MOOCs", desc:"Online courses and micro-credentials from global universities.", tags:["moocs","certificates"], verified:true },
  { id:185, name:"IGNOU", url:"https://www.ignou.ac.in", category:"education", sub:"Higher Education", desc:"Indira Gandhi National Open University for distance and online degrees.", tags:["distance learning","degrees"], verified:true, popular:true },
  { id:186, name:"CBSE", url:"https://www.cbse.gov.in", category:"education", sub:"School Learning", desc:"Central Board of Secondary Education — syllabus, results and circulars.", tags:["board exams","syllabus"], verified:true, popular:true },
  { id:187, name:"DIKSHA", url:"https://diksha.gov.in", category:"education", sub:"School Learning", desc:"National digital platform for school teachers and students with curriculum content.", tags:["curriculum","digital learning"], verified:true },
  { id:188, name:"Doubtnut", url:"https://www.doubtnut.com", category:"education", sub:"Exam Preparation", desc:"Doubt-solving app using photo-based question search for math and science.", tags:["doubt solving","exam prep"], verified:true },
  { id:189, name:"Gradeup (by BYJU'S Exam Prep)", url:"https://gradeup.co", category:"education", sub:"Exam Preparation", desc:"Online test series and study material for government exam aspirants.", tags:["exam prep","test series"], verified:true },
  { id:190, name:"Skillshare", url:"https://www.skillshare.com", category:"education", sub:"Free Courses & MOOCs", desc:"Creative and professional skills courses taught by industry practitioners.", tags:["creative skills","online courses"], verified:true },
  { id:191, name:"Udemy", url:"https://www.udemy.com", category:"education", sub:"Free Courses & MOOCs", desc:"Marketplace for online courses across technology, business and creative skills.", tags:["online courses","marketplace"], verified:true, popular:true },
  { id:192, name:"LinkedIn Learning", url:"https://www.linkedin.com/learning", category:"education", sub:"Free Courses & MOOCs", desc:"Professional development video courses integrated with LinkedIn profiles.", tags:["professional development","courses"], verified:true },
  { id:193, name:"AICTE", url:"https://www.aicte-india.org", category:"education", sub:"Higher Education", desc:"All India Council for Technical Education — regulates technical institutes.", tags:["technical education","regulator"], verified:true },
  // ---------------- JOBS & CAREERS ----------------
  { id:194, name:"Shine.com", url:"https://www.shine.com", category:"jobs", sub:"Job Portals", desc:"Job search portal with resume services and career resources.", tags:["jobs","resume"], verified:true },
  { id:195, name:"TimesJobs", url:"https://www.timesjobs.com", category:"jobs", sub:"Job Portals", desc:"Job listings and recruitment services across industries.", tags:["jobs","recruitment"], verified:true },
  { id:196, name:"Monster India", url:"https://www.monsterindia.com", category:"jobs", sub:"Job Portals", desc:"Job search platform connecting candidates with employers.", tags:["jobs","recruitment"], verified:true },
  { id:197, name:"Foundit", url:"https://www.foundit.in", category:"jobs", sub:"Job Portals", desc:"Job search platform (formerly Monster) for professionals across sectors.", tags:["jobs","careers"], verified:true },
  { id:198, name:"Glassdoor", url:"https://www.glassdoor.co.in", category:"jobs", sub:"Professional Networking", desc:"Company reviews, salary insights and job listings platform.", tags:["company reviews","salaries"], verified:true, popular:true },
  { id:199, name:"Wellfound", url:"https://wellfound.com", category:"jobs", sub:"Job Portals", desc:"Job platform focused on startups and tech talent.", tags:["startups","tech jobs"], verified:true },
  { id:200, name:"Fiverr", url:"https://www.fiverr.com", category:"jobs", sub:"Freelancing", desc:"Global marketplace for freelance services across creative and tech skills.", tags:["freelancing","gig work"], verified:true, popular:true },
  { id:201, name:"Freelancer.com", url:"https://www.freelancer.com", category:"jobs", sub:"Freelancing", desc:"Freelance marketplace connecting clients with independent professionals.", tags:["freelancing","projects"], verified:true },
  { id:202, name:"UPSC", url:"https://upsc.gov.in", category:"jobs", sub:"Government Jobs", desc:"Union Public Service Commission — civil services exam notifications and results.", tags:["civil services","exams"], verified:true, popular:true },
  { id:203, name:"IBPS", url:"https://www.ibps.in", category:"jobs", sub:"Government Jobs", desc:"Institute of Banking Personnel Selection — bank recruitment exams.", tags:["bank jobs","exams"], verified:true },
  // ---------------- TRAVEL & TRANSPORT ----------------
  { id:204, name:"Yatra", url:"https://www.yatra.com", category:"travel", sub:"Flights & Hotels", desc:"Flight, hotel and holiday package booking platform.", tags:["flights","hotels"], verified:true },
  { id:205, name:"Cleartrip", url:"https://www.cleartrip.com", category:"travel", sub:"Flights & Hotels", desc:"Flight and hotel booking platform with simple, fast search.", tags:["flights","hotels"], verified:true },
  { id:206, name:"EaseMyTrip", url:"https://www.easemytrip.com", category:"travel", sub:"Flights & Hotels", desc:"Online travel agency for flight, hotel and holiday bookings.", tags:["flights","hotels"], verified:true, popular:true },
  { id:207, name:"Booking.com", url:"https://www.booking.com", category:"travel", sub:"Flights & Hotels", desc:"Global hotel and accommodation booking platform.", tags:["hotels","accommodation"], verified:true, popular:true },
  { id:208, name:"Airbnb", url:"https://www.airbnb.co.in", category:"travel", sub:"Flights & Hotels", desc:"Marketplace for booking homestays and unique accommodations.", tags:["homestays","accommodation"], verified:true, popular:true },
  { id:209, name:"SpiceJet", url:"https://www.spicejet.com", category:"travel", sub:"Airlines", desc:"Indian low-cost airline for domestic and international flights.", tags:["airline","flights"], verified:true },
  { id:210, name:"Akasa Air", url:"https://www.akasaair.com", category:"travel", sub:"Airlines", desc:"Indian low-cost carrier offering domestic flight bookings.", tags:["airline","flights"], verified:true },
  { id:211, name:"Uber", url:"https://www.uber.com/in/en/", category:"travel", sub:"Local Transit", desc:"Ride-hailing app for cabs and local transportation.", tags:["cabs","rides"], verified:true, popular:true },
  { id:212, name:"Ola", url:"https://www.olacabs.com", category:"travel", sub:"Local Transit", desc:"Indian ride-hailing service for cabs, autos and bikes.", tags:["cabs","rides"], verified:true, popular:true },
  { id:213, name:"Rapido", url:"https://rapido.bike", category:"travel", sub:"Local Transit", desc:"Bike taxi and ride-hailing app for quick local commutes.", tags:["bike taxi","rides"], verified:true, trending:true },
  { id:214, name:"Indian Railways", url:"https://indianrailways.gov.in", category:"travel", sub:"Trains & Buses", desc:"Official portal of Indian Railways with information on trains and services.", tags:["railways","official"], verified:true },
  { id:215, name:"Trainman", url:"https://www.trainman.in", category:"travel", sub:"Trains & Buses", desc:"Train ticket booking app with PNR status and seat availability.", tags:["trains","pnr status"], verified:true },
  { id:216, name:"Trivago", url:"https://www.trivago.in", category:"travel", sub:"Flights & Hotels", desc:"Hotel price comparison search engine.", tags:["hotels","price comparison"], verified:true },
  { id:217, name:"Treebo Hotels", url:"https://www.treebohotels.com", category:"travel", sub:"Flights & Hotels", desc:"Budget hotel chain offering standardized stays across India.", tags:["hotels","budget"], verified:true },
  { id:218, name:"FlixBus India", url:"https://www.flixbus.in", category:"travel", sub:"Trains & Buses", desc:"Intercity bus booking service with long-distance routes.", tags:["bus","intercity"], verified:true },
  { id:219, name:"AbhiBus", url:"https://www.abhibus.com", category:"travel", sub:"Trains & Buses", desc:"Online bus ticket booking platform across Indian routes.", tags:["bus","tickets"], verified:true },
  // ---------------- ENTERTAINMENT ----------------
  { id:220, name:"ZEE5", url:"https://www.zee5.com", category:"entertainment", sub:"Video Streaming", desc:"Streaming platform for movies, originals and regional content.", tags:["streaming","regional"], verified:true, popular:true },
  { id:221, name:"SonyLIV", url:"https://www.sonyliv.com", category:"entertainment", sub:"Video Streaming", desc:"Streaming service for shows, sports and originals from Sony.", tags:["streaming","sports"], verified:true },
  { id:222, name:"Apple Music", url:"https://music.apple.com", category:"entertainment", sub:"Music & Podcasts", desc:"Music streaming service with a large global catalogue.", tags:["music","streaming"], verified:true },
  { id:223, name:"Wynk Music", url:"https://wynk.in", category:"entertainment", sub:"Music & Podcasts", desc:"Music streaming app with Bollywood and regional catalogues.", tags:["music","bollywood"], verified:true },
  { id:224, name:"Audible", url:"https://www.audible.in", category:"entertainment", sub:"Music & Podcasts", desc:"Audiobook and podcast platform with a wide title selection.", tags:["audiobooks","podcasts"], verified:true },
  { id:225, name:"District", url:"https://www.district.in", category:"entertainment", sub:"Live Events & Tickets", desc:"Event discovery and ticketing platform for concerts, dining and shows.", tags:["events","tickets"], verified:true },
  { id:226, name:"Paytm Insider", url:"https://insider.in", category:"entertainment", sub:"Live Events & Tickets", desc:"Event ticketing platform for concerts, comedy shows and festivals.", tags:["events","tickets"], verified:true },
  { id:227, name:"MX Player", url:"https://www.mxplayer.in", category:"entertainment", sub:"Video Streaming", desc:"Free video streaming app for movies, shows and originals.", tags:["streaming","free"], verified:true },
  { id:228, name:"JioCinema", url:"https://www.jiocinema.com", category:"entertainment", sub:"Video Streaming", desc:"Streaming platform for movies, shows and live sports.", tags:["streaming","sports"], verified:true, popular:true },
  { id:229, name:"Twitch", url:"https://www.twitch.tv", category:"entertainment", sub:"Video Sharing", desc:"Live streaming platform for gaming, esports and creator content.", tags:["live streaming","gaming"], verified:true },
  // ---------------- NEWS & MEDIA ----------------
  { id:230, name:"Hindustan Times", url:"https://www.hindustantimes.com", category:"news", sub:"National News", desc:"National daily covering politics, business and current affairs.", tags:["news","national"], verified:true, popular:true },
  { id:231, name:"India Today", url:"https://www.indiatoday.in", category:"news", sub:"National News", desc:"News magazine and digital platform covering national affairs.", tags:["news","national"], verified:true, popular:true },
  { id:232, name:"Livemint", url:"https://www.livemint.com", category:"news", sub:"Business & Markets", desc:"Business newspaper covering markets, economy and companies.", tags:["business","markets"], verified:true },
  { id:233, name:"The Economic Times", url:"https://economictimes.indiatimes.com", category:"news", sub:"Business & Markets", desc:"India's leading business daily covering markets and economy.", tags:["business","markets"], verified:true, popular:true },
  { id:234, name:"Business Standard", url:"https://www.business-standard.com", category:"news", sub:"Business & Markets", desc:"Business and financial news covering markets and policy.", tags:["business","policy"], verified:true },
  { id:235, name:"Financial Express", url:"https://www.financialexpress.com", category:"news", sub:"Business & Markets", desc:"Business daily covering finance, markets and industry news.", tags:["business","finance"], verified:true },
  { id:236, name:"Dainik Bhaskar", url:"https://www.bhaskar.com", category:"news", sub:"National News", desc:"Widely circulated Hindi-language newspaper covering national news.", tags:["news","hindi"], verified:true, popular:true },
  { id:237, name:"ABP News", url:"https://news.abplive.com", category:"news", sub:"National News", desc:"Hindi news channel and digital platform for national coverage.", tags:["news","hindi"], verified:true },
  { id:238, name:"Sportstar", url:"https://sportstar.thehindu.com", category:"news", sub:"Sports News", desc:"Sports magazine covering cricket, football and other sports.", tags:["sports","cricket"], verified:true },
  // ---------------- HEALTH ----------------
  { id:239, name:"Netmeds", url:"https://www.netmeds.com", category:"health", sub:"Pharmacy & Medicine", desc:"Online pharmacy for medicine delivery and health products.", tags:["medicine","pharmacy"], verified:true },
  { id:240, name:"Truemeds", url:"https://www.truemeds.in", category:"health", sub:"Pharmacy & Medicine", desc:"Affordable generic medicine delivery platform.", tags:["medicine","generic"], verified:true },
  { id:241, name:"Cult.fit", url:"https://www.cult.fit", category:"health", sub:"Fitness & Wellness", desc:"Fitness classes, gyms and wellness programs booking platform.", tags:["fitness","gym"], verified:true, popular:true },
  { id:242, name:"HealthifyMe", url:"https://www.healthifyme.com", category:"health", sub:"Fitness & Wellness", desc:"AI-based nutrition and fitness coaching app.", tags:["nutrition","fitness"], verified:true },
  { id:243, name:"Fortis Healthcare", url:"https://www.fortishealthcare.com", category:"health", sub:"Hospitals & Research", desc:"Private hospital chain offering specialty medical care.", tags:["hospital","specialty care"], verified:true },
  { id:244, name:"Max Healthcare", url:"https://www.maxhealthcare.in", category:"health", sub:"Hospitals & Research", desc:"Multi-specialty hospital network across India.", tags:["hospital","specialty care"], verified:true },
  { id:245, name:"Manipal Hospitals", url:"https://www.manipalhospitals.com", category:"health", sub:"Hospitals & Research", desc:"Hospital chain offering multi-specialty treatment and diagnostics.", tags:["hospital","diagnostics"], verified:true },
  { id:246, name:"Lybrate", url:"https://www.lybrate.com", category:"health", sub:"Doctor Consultation", desc:"Platform to find doctors and book online consultations.", tags:["doctors","consultation"], verified:true },
  { id:247, name:"Ayushman Bharat (PM-JAY)", url:"https://pmjay.gov.in", category:"health", sub:"Government Health Info", desc:"National health insurance scheme portal for eligible families.", tags:["health insurance","government scheme"], verified:true },
  { id:248, name:"Thyrocare", url:"https://www.thyrocare.com", category:"health", sub:"Pharmacy & Medicine", desc:"Diagnostic lab chain offering health checkups and test bookings.", tags:["diagnostics","lab tests"], verified:true },
  // ---------------- FOOD & GROCERY ----------------
  { id:249, name:"Domino's Pizza India", url:"https://www.dominos.co.in", category:"food", sub:"Food Delivery", desc:"Pizza delivery chain with online ordering and tracking.", tags:["pizza","delivery"], verified:true, popular:true },
  { id:250, name:"McDonald's India", url:"https://www.mcdonaldsindia.com", category:"food", sub:"Food Delivery", desc:"Fast-food chain with online ordering and delivery.", tags:["fast food","delivery"], verified:true },
  { id:251, name:"FreshToHome", url:"https://www.freshtohome.com", category:"food", sub:"Specialty Food", desc:"Fresh fish, meat and poultry delivery direct from source.", tags:["seafood","meat"], verified:true },
  { id:252, name:"Country Delight", url:"https://countrydelight.in", category:"food", sub:"Grocery Delivery", desc:"Farm-fresh milk and grocery subscription delivery service.", tags:["milk","subscription"], verified:true },
  { id:253, name:"Milkbasket", url:"https://www.milkbasket.com", category:"food", sub:"Grocery Delivery", desc:"Daily micro-delivery service for milk, groceries and essentials.", tags:["milk","daily delivery"], verified:true },
  { id:254, name:"Nature's Basket", url:"https://www.naturesbasket.co.in", category:"food", sub:"Grocery Delivery", desc:"Premium grocery store for gourmet and imported food products.", tags:["gourmet","grocery"], verified:true },
  { id:255, name:"Behrouz Biryani", url:"https://www.behrouzbiryani.com", category:"food", sub:"Food Delivery", desc:"Cloud-kitchen brand specializing in biryani delivery.", tags:["biryani","delivery"], verified:true },
  { id:256, name:"Spencer's Retail", url:"https://www.spencers.in", category:"food", sub:"Grocery Delivery", desc:"Retail chain offering grocery, fresh produce and daily essentials.", tags:["grocery","retail"], verified:true },
  // ---------------- AI TOOLS ----------------
  { id:257, name:"Meta AI", url:"https://www.meta.ai", category:"ai", sub:"AI Assistants", desc:"Meta's AI assistant integrated across its apps and standalone site.", tags:["ai assistant","meta"], verified:true },
  { id:258, name:"Grok", url:"https://grok.com", category:"ai", sub:"AI Assistants", desc:"xAI's conversational AI assistant integrated with X.", tags:["ai assistant","xai"], verified:true, trending:true },
  { id:259, name:"Mistral AI", url:"https://mistral.ai", category:"ai", sub:"AI Assistants", desc:"French AI lab offering open and commercial language models.", tags:["ai assistant","open models"], verified:true },
  { id:260, name:"DeepSeek", url:"https://www.deepseek.com", category:"ai", sub:"AI Assistants", desc:"Chinese AI lab's chat assistant and open-weight language models.", tags:["ai assistant","open models"], verified:true, trending:true },
  { id:261, name:"Midjourney", url:"https://www.midjourney.com", category:"ai", sub:"AI Creative Tools", desc:"AI image generation tool for creating art from text prompts.", tags:["ai art","image generation"], verified:true, popular:true },
  { id:262, name:"Runway", url:"https://runwayml.com", category:"ai", sub:"AI Creative Tools", desc:"AI-powered video generation and editing platform.", tags:["ai video","generation"], verified:true },
  { id:263, name:"ElevenLabs", url:"https://elevenlabs.io", category:"ai", sub:"AI Creative Tools", desc:"AI voice generation and text-to-speech platform.", tags:["ai voice","text to speech"], verified:true },
  { id:264, name:"Hugging Face", url:"https://huggingface.co", category:"ai", sub:"AI Developer Tools", desc:"Platform and hub for open-source AI models and datasets.", tags:["ai models","open source"], verified:true, popular:true },
  { id:265, name:"GitHub Copilot", url:"https://github.com/features/copilot", category:"ai", sub:"AI Developer Tools", desc:"AI pair-programmer that suggests code inside your editor.", tags:["ai coding","developer tools"], verified:true, popular:true },
  { id:266, name:"Sarvam AI", url:"https://www.sarvam.ai", category:"ai", sub:"Indian AI", desc:"Indian AI company building voice and language models for Indian languages.", tags:["ai assistant","indian languages"], verified:true, trending:true },
  // ---------------- SOCIAL & MESSAGING ----------------
  { id:267, name:"Snapchat", url:"https://www.snapchat.com", category:"social", sub:"Social Networking", desc:"Photo and video messaging app known for disappearing content.", tags:["photos","messaging"], verified:true },
  { id:268, name:"Pinterest", url:"https://www.pinterest.com", category:"social", sub:"Social Networking", desc:"Visual discovery platform for ideas, inspiration and bookmarking.", tags:["inspiration","images"], verified:true, popular:true },
  { id:269, name:"Reddit", url:"https://www.reddit.com", category:"social", sub:"Social Networking", desc:"Community-driven discussion platform organized into topic forums.", tags:["forums","discussion"], verified:true, popular:true },
  { id:270, name:"Discord", url:"https://discord.com", category:"social", sub:"Messaging", desc:"Voice, video and text chat platform built around communities.", tags:["chat","communities"], verified:true, popular:true },
  { id:271, name:"Signal", url:"https://signal.org", category:"social", sub:"Messaging", desc:"Privacy-focused encrypted messaging app.", tags:["messaging","privacy"], verified:true },
  { id:272, name:"Moj", url:"https://mojapp.in", category:"social", sub:"Regional Social", desc:"Indian short-video app for regional-language content creation.", tags:["short video","regional"], verified:true },
  // ---------------- REAL ESTATE ----------------
  { id:273, name:"Square Yards", url:"https://www.squareyards.com", category:"realestate", sub:"Property Listings", desc:"Real estate marketplace for buying, selling and renting properties.", tags:["property","marketplace"], verified:true },
  { id:274, name:"PropTiger", url:"https://www.proptiger.com", category:"realestate", sub:"Property Listings", desc:"Property search and advisory platform for homebuyers.", tags:["property","advisory"], verified:true },
  { id:275, name:"Roof and Floor", url:"https://www.roofandfloor.com", category:"realestate", sub:"Property Listings", desc:"Property listing portal by The Hindu Group for buying and renting.", tags:["property","listings"], verified:true },
  { id:276, name:"Livspace", url:"https://www.livspace.com", category:"realestate", sub:"Interior Design & Home Services", desc:"Home interior design and renovation platform.", tags:["interior design","renovation"], verified:true, popular:true },
  { id:277, name:"Urban Company", url:"https://www.urbancompany.com", category:"realestate", sub:"Interior Design & Home Services", desc:"On-demand home services including cleaning, repair and beauty.", tags:["home services","on-demand"], verified:true, popular:true, trending:true },
  { id:278, name:"Sulekha", url:"https://www.sulekha.com", category:"realestate", sub:"Interior Design & Home Services", desc:"Local services marketplace connecting users with verified professionals.", tags:["local services","marketplace"], verified:true },
  // ---------------- UTILITIES & BILLS ----------------
  { id:279, name:"Tata Power", url:"https://www.tatapower.com", category:"utilities", sub:"Bill Payments", desc:"Electricity bill payment and account management for Tata Power consumers.", tags:["electricity","bill payment"], verified:true },
  { id:280, name:"BSES Delhi", url:"https://www.bsesdelhi.com", category:"utilities", sub:"Bill Payments", desc:"Electricity distribution and bill payment portal for Delhi consumers.", tags:["electricity","delhi"], verified:true },
  { id:281, name:"Mahadiscom (MSEDCL)", url:"https://www.mahadiscom.in", category:"utilities", sub:"Bill Payments", desc:"Electricity bill payment portal for Maharashtra consumers.", tags:["electricity","maharashtra"], verified:true },
  { id:282, name:"Indane Gas", url:"https://www.indane.co.in", category:"utilities", sub:"Bill Payments", desc:"LPG cylinder booking and account services from Indian Oil.", tags:["lpg","gas booking"], verified:true },
  { id:283, name:"BSNL", url:"https://www.bsnl.co.in", category:"utilities", sub:"Telecom Recharge", desc:"State-run telecom operator for mobile and broadband recharge.", tags:["recharge","telecom"], verified:true },
  { id:284, name:"MTNL", url:"https://www.mtnl.net.in", category:"utilities", sub:"Telecom Recharge", desc:"Telecom services and bill payment for Delhi and Mumbai circles.", tags:["recharge","telecom"], verified:true },
  // ---------------- PRODUCTIVITY & DEV ----------------
  { id:285, name:"Microsoft 365", url:"https://www.microsoft.com/microsoft-365", category:"productivity", sub:"Docs & Notes", desc:"Productivity suite with Word, Excel, PowerPoint and cloud storage.", tags:["office suite","docs"], verified:true, popular:true },
  { id:286, name:"Google Workspace", url:"https://workspace.google.com", category:"productivity", sub:"Docs & Notes", desc:"Cloud productivity suite with Gmail, Docs, Sheets and Meet.", tags:["office suite","cloud"], verified:true, popular:true },
  { id:287, name:"Slack", url:"https://slack.com", category:"productivity", sub:"Team Collaboration", desc:"Business messaging platform for team communication.", tags:["messaging","teams"], verified:true, popular:true },
  { id:288, name:"Trello", url:"https://trello.com", category:"productivity", sub:"Team Collaboration", desc:"Visual project management tool using boards and cards.", tags:["project management","kanban"], verified:true },
  { id:289, name:"Asana", url:"https://asana.com", category:"productivity", sub:"Team Collaboration", desc:"Work management platform for tracking team projects and tasks.", tags:["project management","tasks"], verified:true },
  { id:290, name:"Jira", url:"https://www.atlassian.com/software/jira", category:"productivity", sub:"Team Collaboration", desc:"Issue tracking and agile project management tool by Atlassian.", tags:["issue tracking","agile"], verified:true },
  { id:291, name:"Figma", url:"https://www.figma.com", category:"productivity", sub:"Design Tools", desc:"Collaborative interface design and prototyping tool.", tags:["design","prototyping"], verified:true, popular:true },
  { id:292, name:"Adobe Express", url:"https://www.adobe.com/express", category:"productivity", sub:"Design Tools", desc:"Quick design tool for graphics, videos and social content.", tags:["design","graphics"], verified:true },
  { id:293, name:"GitLab", url:"https://gitlab.com", category:"productivity", sub:"Code & Dev", desc:"DevOps platform for source code management and CI/CD.", tags:["code","devops"], verified:true },
  { id:294, name:"Bitbucket", url:"https://bitbucket.org", category:"productivity", sub:"Code & Dev", desc:"Git code hosting and collaboration tool by Atlassian.", tags:["code","git"], verified:true },
  { id:295, name:"AWS", url:"https://aws.amazon.com", category:"productivity", sub:"Hosting & Deployment", desc:"Amazon's cloud computing platform for hosting and infrastructure.", tags:["cloud","hosting"], verified:true, popular:true },
  { id:296, name:"DigitalOcean", url:"https://www.digitalocean.com", category:"productivity", sub:"Hosting & Deployment", desc:"Cloud hosting platform popular with developers and startups.", tags:["cloud","hosting"], verified:true },
  { id:297, name:"Dropbox", url:"https://www.dropbox.com", category:"productivity", sub:"Cloud Storage", desc:"Cloud file storage and sharing service.", tags:["cloud storage","files"], verified:true, popular:true },
  { id:298, name:"Microsoft OneDrive", url:"https://www.microsoft.com/en-us/microsoft-365/onedrive/online-cloud-storage", category:"productivity", sub:"Cloud Storage", desc:"Cloud storage integrated with Windows and Microsoft 365.", tags:["cloud storage","files"], verified:true },
  { id:299, name:"Adobe Acrobat", url:"https://www.adobe.com/acrobat.html", category:"productivity", sub:"PDF Tools", desc:"PDF creation, editing and e-signature tool by Adobe.", tags:["pdf","editing"], verified:true },
  { id:300, name:"Smallpdf", url:"https://smallpdf.com", category:"productivity", sub:"PDF Tools", desc:"Free online tools to compress, convert and edit PDFs.", tags:["pdf","tools"], verified:true },
];

